// this route was generated by AI and not my code.
"use client";

import { motion } from "motion/react";

export default function ScreenEdgeGlow() {
  return (
    <div className="pointer-events-none fixed top-2.5 right-2.5 bottom-2.5 left-2.5 z-50 opacity-80">
      <svg className="absolute inset-0 h-full w-full" aria-hidden="true">
        <defs>
          <filter id="edge-glow" x="-100%" y="-100%" width="300%" height="300%">
            <feGaussianBlur in="SourceGraphic" stdDeviation="4" result="blur" />

            <feMerge>
              <feMergeNode in="blur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>

        {/* Your normal static border */}
        <rect
          x="0.5"
          y="0.5"
          width="calc(100% - 1px)"
          height="calc(100% - 1px)"
          fill="none"
          stroke="rgba(156, 163, 175, 0.35)"
          strokeWidth="0.2"
        />

        {/* Sharp concentrated light */}
        <motion.rect
          x="0.5"
          y="0.5"
          width="calc(100% - 1px)"
          height="calc(100% - 1px)"
          fill="none"
          stroke="rgba(255,255,255,0.95)"
          strokeWidth="1.5"
          strokeLinecap="round"
          pathLength={1}
          strokeDasharray="0.012 0.988"
          initial={{ strokeDashoffset: 0 }}
          animate={{ strokeDashoffset: -1 }}
          transition={{
            duration: 20,
            repeat: Infinity,
            ease: "linear",
          }}
        />
      </svg>
    </div>
  );
}
